[versions]
kotlin = "2.0.0"
technical-analysis = "1.1.0"

multik = "0.2.3"
dataframe = "1.0.0-Beta4"

jupiter = "5.8.1"
kmm-publish = "0.32.0"
dokka = "2.0.0"

[libraries]

# gradle
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version= "2.3.21" }

# data
multik-core = { module = "org.jetbrains.kotlinx:multik-core", version.ref = "multik" }
multik-default = { module = "org.jetbrains.kotlinx:multik-default", version.ref = "multik" }
multik-kotlin= { module = "org.jetbrains.kotlinx:multik-kotlin", version.ref = "multik" }
dataframe = { module = "org.jetbrains.kotlinx:dataframe", version.ref = "dataframe" }

# tests
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter"}
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter"}

[plugins]
kmm-publish = { id = "com.vanniktech.maven.publish", version.ref = "kmm-publish"}
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka"}
